default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
  
development:
  <<: *default
  database: i_clone_development

test:
  <<: *default
  database: i_clone_test

production:
  <<: *default
  database: i_clone_production
  username: i_clone
  password: <%= ENV['I_CLONE_DATABASE_PASSWORD'] %>
